In [ ]:
pip install transformers

In [2]:
from transformers import pipeline

#### Text Classification

In [5]:
classifier = pipeline('text-classification')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

In [10]:
import pandas as pd

In [11]:
text = 'It was possible for him. So he did it.'

In [12]:
result = classifier(text)

In [13]:
df = pd.DataFrame(result)

In [14]:
df

      label    score
0  POSITIVE  0.97479

In [15]:
text = 'Nothing is possible without these efforts!'
result = classifier(text)
df = pd.DataFrame(result)
df

      label     score
0  POSITIVE  0.994458

In [16]:
text = 'I think it is impossible for him. So just avoid it.'
result = classifier(text)
df = pd.DataFrame(result)
df

      label     score
0  NEGATIVE  0.999727

In [17]:
text = 'It was so impressive but not upto the mark.'
result = classifier(text)
df = pd.DataFrame(result)
df

      label     score
0  NEGATIVE  0.983271

In [18]:
text = '''disney's 35th animated feature-- a retooling of the olympian legend crossed with , well , the superman story-- is surprisingly soft at the center . 
great wit , great art , and a great villain ( james woods as hades , lord of the underworld and local lounge act ) can't quite stifle the yawns induced by a bland hero , his colorfully monotonous sidekick ( danny devito as the satyrical trainer phil ) , and a largely unremarkable soundtrack . 
 ( none of the alan menken/david zippel tunes are particular- ly noteworthy . 
some lack lyrical snap . 
others need more memorable melodies . 
boring ballads we expect , but boring production numbers , too ? ) 
so , hercules is a bit of a long sit , but you won't stay bored . 
the highlights include a nifty round of animated action ( herc battling a cgi hydra ) , a steady stream of anachronisms ( " somebody call ix-i-i " ) and pop references ( " let's get ready to rumble ! " ) a la aladdin , and several long-overdue jabs at the mouse's marketing and merchandising depart- ments . 
while not as rock-solid as hunchback , it's a still a new world of improvement over pocohontas . 
directed by ron clements and john musker , with voice credits including tate donovan , susan egan , bob goldthwait , matt frewer , samantha eggar , paul shaffer , and , as lighting bolt zeus , rip torn , who's having a very good summer , also appearing in trial and error and men in black . '''
result = classifier(text)
df = pd.DataFrame(result)
df

      label     score
0  POSITIVE  0.991984

In [19]:
text = '''i was going to see ram shrasta on the big screen last night , but before that i stopped into my video store to rent some movies . 
luckily , my video guy was in the middle or recording ram shrasta ! 
i knew it was going to be a bad print with only half-faces and poor sound quality , but i couldn't help myself . . . 
i got it . 
well , after watching it ( it indeed was a bad print ) i was glad i didn't dish out $7 to waste three hours of my time sitting in a bad theatre watching a bad movie . 
this movie really sucks . 
it had so many inconsistencies it was driving me crazy ! ! 
for example , how can jackie shroff grow two feet of hair in just three or four days ? 
jackie shroff looked really stupid with his steven seagal ponytail . 
the songs are bad , the acting is bad ( especially deepti bhatnagar's ) , and the direction is the worst of all . 
the comedy scenes with jagdish and johnny lever just made me want to throw up . 
i didn't even finish the movie . . . 
i couldn't take it anymore . 
note : but if anyone out there liked aatish ( by the same director ) , i guess you'd like this movie . 
it's practically the same except that sanjay dutt is replaced with jackie shroff . 
aditya panscholi is the sidekick again . 
 ( i was going to give it a zero , but i personally like jackie shroff , so i loosened up a little . 
he looked fresh , wore good clothes ( as always ) , and his performance , even though it wasn't his best , was the only saving grace of the movie ) '''
result = classifier(text)
df = pd.DataFrame(result)
df

      label    score
0  NEGATIVE  0.99961

#### Named Entity Recognition

In [22]:
ner = pipeline('token-classification')

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision f2482bf (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [23]:
text = '''Mark Zukerberg will meet Aditya Joshi
on Monday 25 November 2025, 10am for $3 Trillion deal
at Pune for second time.'''

In [24]:
result = ner(text)
df = pd.DataFrame(result)
df

   entity     score  index    word  start  end
0   I-PER  0.999749      1    Mark      0    4
1   I-PER  0.999260      2       Z      5    6
2   I-PER  0.988053      3   ##uke      6    9
3   I-PER  0.764807      4  ##rber      9   13
4   I-PER  0.993470      5     ##g     13   14
5   I-PER  0.999741      8      Ad     25   27
6   I-PER  0.998847      9   ##ity     27   30
7   I-PER  0.999252     10     ##a     30   31
8   I-PER  0.999298     11    Josh     32   36
9   I-PER  0.995793     12     ##i     36   37
10  I-LOC  0.989665     30    Pune     95   99

#### Question-Answering

In [33]:
qa = pipeline('question-answering')

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.
/home/mitu/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [30]:
text = 'New Delhi is capital city of India.'
question = 'What is capital city of India?'
result_qa = qa(question=question, context=text)
df = pd.DataFrame([result_qa])
df

      score  start  end     answer
0  0.996635      0    9  New Delhi

In [31]:
text = '''Antarctica (/ænˈtɑːrktɪkə/ ⓘ)[note 1] is Earth's southernmost and least-populated continent. Situated almost entirely south of the Antarctic Circle and surrounded by the Southern Ocean (also known as the Antarctic Ocean), it contains the geographic South Pole. Antarctica is the fifth-largest continent, being about 40% larger than Europe, and has an area of 14,200,000 km2 (5,500,000 sq mi). Most of Antarctica is covered by the Antarctic ice sheet, with an average thickness of 1.9 km (1.2 mi).
Antarctica is, on average, the coldest, driest, and windiest of the continents, and has the highest average elevation. It is mainly a polar desert, with annual precipitation of over 200 mm (8 in) along the coast and far less inland. About 70% of the world's freshwater reserves are frozen in Antarctica, which, if melted, would raise global sea levels by almost 60 metres (200 ft). Antarctica holds the record for the lowest measured temperature on Earth, −89.2 °C (−128.6 °F). The coastal regions can reach temperatures over 10 °C (50 °F) in the summer. Native species of animals include mites, nematodes, penguins, seals and tardigrades. Where vegetation occurs, it is mostly in the form of lichen or moss.'''
question = 'What is lowest temperature on earth?'
result_qa = qa(question=question, context=text)
df = pd.DataFrame([result_qa])
df

      score  start  end    answer
0  0.633267    953  961  −89.2 °C

['audio-classification', 'automatic-speech-recognition', 'conversational', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-to-image', 'image-to-text', 'mask-generation', 'ner', 'object-detection', 'question-answering', 'sentiment-analysis', 'summarization', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'text2text-generation', 'token-classification', 'translation', 'video-classification', 'visual-question-answering', 'vqa', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection', 'translation_XX_to_YY']

#### Translation

In [35]:
trans = pipeline('translation_en_to_fr')

No model was supplied, defaulted to google-t5/t5-base and revision 686f1db (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.
/home/mitu/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

/home/mitu/.local/lib/python3.10/site-packages/transformers/models/t5/tokenization_t5_fast.py:171: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on google-t5/t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(

In [38]:
translator = pipeline(
    "translation", 
    model="facebook/m2m100_418M", 
    src_lang="en", 
    tgt_lang="mr"
)

text = "Hello friends! How are you?"

result = translator(text)

print("Translated Text:", result[0]['translation_text'])

/home/mitu/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Translated Text: नमस्कार मित्र, तुम्ही कसा आहात?

#### Conversation

In [40]:
from transformers import Conversation

In [41]:
converse = pipeline('conversational')

No model was supplied, defaulted to microsoft/DialoGPT-medium and revision 8bada3b (https://huggingface.co/microsoft/DialoGPT-medium).
Using a pipeline without specifying a model name and revision in production is not recommended.
/home/mitu/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/863M [00:00<?, ?B/s]

KeyboardInterrupt: